// P-Pass design tokens — generated by hand from assets/design/tokens.json
// (single source of truth; edit that first). Warm paper, ink text, ONE
// green that means safe. Mobile scale: body >=17sp, tap targets >=56dp.
package com.hawkeyexb.ppass.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object PPColor {
    val Paper = Color(0xFFFBF8F2)
    val Canvas = Color(0xFFEFE9DF)
    val Linen = Color(0xFFF1ECE3)
    val SurfaceDark = Color(0xFF211E1A)

    val Ink = Color(0xFF171512)
    val InkHover = Color(0xFF2A2621)
    val Ink60 = Color(0xFF4A453E)
    val Ink40 = Color(0xFF6B655C)
    val Hairline = Color(0xFFE0D8CB)

    // The three meaning colours — nothing else carries meaning.
    val Safe = Color(0xFF2E6B4F)
    val SafeBg = Color(0xFFE4F1E8)
    val Waiting = Color(0xFFC9761E)
    val WaitingBg = Color(0xFFF7EBDA)
    val Act = Color(0xFFB5341F)
    val ActBg = Color(0xFFF7E2DE)
    val Idle = Color(0xFF8A857C)
    val IdleBg = Color(0xFFEDE8DF)

    val Border = Color(0x1F171512)       // rgba(23,21,18,.12)
    val BorderStrong = Color(0x3D171512) // rgba(23,21,18,.24)
    val Divider = Color(0x1A171512)      // rgba(23,21,18,.10)
    val PaperDim = Color(0x9EFBF8F2)     // paper at .62 for dark surfaces
}

object PPSize {
    val BodyMin = 17.sp
    val BodyZh = 21.sp
    val Headline = 36.sp
    val TapMin = 56.dp
    val RadiusCard = 20.dp
    val RadiusControl = 20.dp
}
