//! msg_key dictionary — the single registry of user-visible message keys.
//!
//! Every key registered here MUST have a translation in both
//! `assets/i18n/en.json` and `assets/i18n/zh.json`; this is enforced by
//! [`crate::assert_all_keys_translated`], which runs as a test.

/// Registers msg_keys as compile-time constants and collects them into
/// [`ALL`] so coverage tests can iterate the full dictionary.
macro_rules! msg_keys {
    ($($(#[$doc:meta])* $name:ident => $key:literal),+ $(,)?) => {
        $($(#[$doc])* pub const $name: &str = $key;)+

        /// Every registered msg_key.
        pub const ALL: &[&str] = &[$($key),+];
    };
}

msg_keys! {
    /// Peer NodeId is not in the device whitelist (or was revoked).
    ERR_NOT_AUTHORIZED => "err.not_authorized",
    /// Peer attempted an operation that requires pairing first.
    ERR_NOT_PAIRED => "err.not_paired",
    /// Storage-side disk has no room for further ingest.
    ERR_DISK_FULL => "err.disk_full",
    /// Method exists in no shipped version, or is not implemented yet
    /// (a newer client talking to an older storage daemon).
    ERR_UNSUPPORTED => "err.unsupported",
    /// A backup batch could not be completed (transfer or ingest failed);
    /// the client retries — the pipeline is idempotent.
    ERR_BACKUP_FAILED => "err.backup_failed",
    /// NET-10 (#128): a pairing request nobody confirmed within the
    /// desktop's pending window (`pair.status` → expired). Phone-perspective.
    ERR_PAIR_EXPIRED => "err.pair_expired",
    /// NET-10 (#128): `pair.status` → not_found — the desktop service
    /// restarted and its in-memory pairing ledger is gone. Phone-perspective.
    ERR_PAIR_RESTARTED => "err.pair_restarted",
    /// Connected to the storage daemon over a direct (or LAN) path.
    DIAG_ONLINE_DIRECT => "diag.online_direct",
    /// Connected, but through a relay — bandwidth may be limited.
    DIAG_ONLINE_RELAY => "diag.online_relay",
    /// Storage daemon unreachable; UI shows last_seen in human terms.
    /// Phone-perspective (the phone is looking at the storage computer).
    DIAG_STORAGE_OFFLINE => "diag.storage_offline",
    /// Media pipeline is (re)indexing the library. Phone-perspective.
    DIAG_INDEXING => "diag.indexing",
    /// A pairing request is waiting for owner confirmation.
    /// Phone-perspective ("waiting on the storage computer").
    DIAG_PAIRING => "diag.pairing",

    // ── Desktop-perspective variants (T-042b) ─────────────────────────
    // The phone-perspective keys above read oddly ON the storage computer
    // itself ("存储电脑离线了" shown by the storage computer is nonsense).
    // The desktop shell maps STATE_KEYS to these; msg_key sharing stays,
    // the dictionary gains per-surface variants. Placeholder-free on
    // purpose: the daemon status payload carries no progress/last_seen
    // values, so a placeholder would render as a literal "{progress}".
    /// Desktop shell: this computer's network link is down.
    DIAG_DESKTOP_STORAGE_OFFLINE => "diag.desktop.storage_offline",
    /// Desktop shell: a device is waiting for the owner to confirm pairing.
    DIAG_DESKTOP_PAIRING => "diag.desktop.pairing",
    /// Desktop shell: the library is being indexed (no progress value).
    DIAG_DESKTOP_INDEXING => "diag.desktop.indexing",
    /// Desktop shell: this computer's disk is full.
    DIAG_DESKTOP_DISK_FULL => "diag.desktop.disk_full",

    // ── Desktop shell UI copy (T-042b: finish the screen) ─────────────
    // UI-layer strings that were hardcoded zh in App.svelte — half-migrated
    // (locale-aware badge + zh buttons) is worse than not migrated.
    UI_OFFLINE_BANNER => "ui.offline_banner",
    UI_OFFLINE_ACTION => "ui.offline_action",
    UI_START_SERVICE => "ui.start_service",
    UI_STARTING => "ui.starting",
    UI_REFRESH_HINT => "ui.refresh_hint",
    UI_PAIRED_COUNT => "ui.paired_count",
    UI_REVOKED_COUNT => "ui.revoked_count",
    UI_PENDING_PAIRS => "ui.pending_pairs",
    UI_ALLOW => "ui.allow",
    /// DEV-04: owner approves a device that has paired before. 标题说
    /// 「请求重新连接」时按钮不能还说「允许加入」——老设备本来就在
    /// 列表里，"加入"这个动词在那一屏是错的。
    UI_ALLOW_RECONNECT => "ui.allow_reconnect",
    UI_DENY => "ui.deny",
    /// DEV-01: owner picks "replace the old device" in the confirm dialog.
    /// DEV-01: owner picks "join as a brand-new device" instead.
    UI_ADD_DEVICE => "ui.add_device",
    UI_GENERATE_QR => "ui.generate_qr",
    UI_QR_FALLBACK => "ui.qr_fallback",
    UI_QR_HINT => "ui.qr_hint",
    UI_QR_PHONE_VERSION => "ui.qr_phone_version",
    UI_DEVICES => "ui.devices",
    UI_NO_DEVICES => "ui.no_devices",
    UI_REVOKED_TAG => "ui.revoked_tag",
    UI_REMOVE => "ui.remove",
    UI_SETTINGS => "ui.settings",
    UI_OPEN_LIBRARY => "ui.open_library",
    UI_CHANGE_LIBRARY => "ui.change_library",
    UI_LOGS_HINT => "ui.logs_hint",
    UI_STOP_SERVICE => "ui.stop_service",
    UI_STOP_HINT => "ui.stop_hint",
    UI_STOP_CONFIRM_TITLE => "ui.stop_confirm_title",
    UI_STOP_CONFIRM_BODY => "ui.stop_confirm_body",
    // UX-04: 桌面顶部徽章的服务态（运行中）——连接状态不再上徽章。
    UI_SERVICE_RUNNING => "ui.service_running",
    UI_SERVICE_STOPPED => "ui.service_stopped",
    UI_STOP_FAILED => "ui.stop_failed",
    UI_START_FAILED => "ui.start_failed",
    UI_PAIR_FAILED => "ui.pair_failed",
    UI_PAIR_ALLOWED => "ui.pair_allowed",
    UI_PAIR_DENIED => "ui.pair_denied",
    UI_CONFIRM_FAILED => "ui.confirm_failed",
    UI_REVOKE_CONFIRM_TITLE => "ui.revoke_confirm_title",
    UI_REVOKE_CONFIRM_BODY => "ui.revoke_confirm_body",
    UI_REVOKED => "ui.revoked",
    UI_REVOKE_FAILED => "ui.revoke_failed",
    /// NAME-01: 设备改名（decisions ② ID 与显示名分离）。
    UI_RENAME => "ui.rename",
    UI_RENAME_SAVED => "ui.rename_saved",
    UI_RENAME_FAILED => "ui.rename_failed",
    UI_OPEN_FAILED => "ui.open_failed",
    UI_CHANGE_TITLE => "ui.change_title",
    UI_CHANGE_BODY => "ui.change_body",
    UI_CHANGE_SAVED => "ui.change_saved",
    UI_SAVE_FAILED => "ui.save_failed",
    UI_LOGS_EXPORTED => "ui.logs_exported",
    UI_EXPORT_FAILED => "ui.export_failed",
    UI_STATUS => "ui.status",
    UI_LIBRARY_DIR_UNKNOWN => "ui.library_dir_unknown",
    // ── Desktop self-update flow (UPD-01c) ────────────────────────────
    UI_UPDATE_AVAILABLE => "ui.update_available",
    UI_UPDATE_INSTALLED => "ui.update_installed",
    UI_UPDATE_FAILED => "ui.update_failed",
    /// REL-07: the update *check* itself failed (upstream 5xx / network) —
    /// distinct from "no new version".
    UI_UPDATE_CHECK_FAILED => "ui.update_check_failed",
    // W1 (2026-08-26): the Windows-specific "a background process still
    // holds the file" failure mode of the update flow — see App.svelte
    // checkForUpdate()'s pause_daemon_for_update/resume_daemon_after_update
    // dance and its file-locked heuristic.
    UI_UPDATE_FAILED_FILE_LOCKED => "ui.update_failed_file_locked",
    // ── Desktop daemon restart after shell update (DAE-04) ───────────
    UI_RESTART_SERVICE => "ui.restart_service",
    UI_RESTART_SERVICE_BTN => "ui.restart_service_btn",
    UI_RESTARTING_SERVICE => "ui.restarting_service",
    UI_RESTART_SERVICE_HINT => "ui.restart_service_hint",
    UI_RESTART_SERVICE_CONFIRM_TITLE => "ui.restart_service_confirm_title",
    UI_RESTART_SERVICE_CONFIRM_BODY => "ui.restart_service_confirm_body",
    UI_RESTART_SERVICE_OK => "ui.restart_service_ok",
    UI_RESTART_SERVICE_NO_CHANGE => "ui.restart_service_no_change",
    UI_RESTART_SERVICE_STARTED => "ui.restart_service_started",
    UI_RESTART_SERVICE_FAILED => "ui.restart_service_failed",
    // ── Desktop photos page (DESK-03) + env badge (DESK-02 收编债) ────
    UI_ENV_BADGE_TEST => "ui.env_badge_test",
    UI_NAV_PHOTOS => "ui.nav_photos",
    UI_PHOTOS_COUNT => "ui.photos_count",
    UI_PHOTOS_TODAY => "ui.photos_today",
    // 2026-08-18（用户反馈②）：照片墙分组从三档细化到五档。
    UI_PHOTOS_YESTERDAY => "ui.photos_yesterday",
    UI_PHOTOS_WEEK => "ui.photos_week",
    UI_PHOTOS_MONTH => "ui.photos_month",
    UI_PHOTOS_EARLIER => "ui.photos_earlier",
    UI_PHOTOS_EMPTY => "ui.photos_empty",
    UI_PHOTOS_OPEN_IN_FINDER => "ui.photos_open_in_finder",
    /// 设计稿 v2：照片页副标题 = 张数 + 真实库路径。
    UI_PHOTOS_COUNT_PATH => "ui.photos_count_path",
    /// 设计稿 v2：lede 右侧「在 Finder 中打开」。
    UI_PHOTOS_OPEN_LIBRARY => "ui.photos_open_library",
    /// 设计稿 v2：配对横幅点名设备名。
    UI_PENDING_BANNER_TEXT => "ui.pending_banner_text",
    /// 设计稿 v2：设备页副标题——已配对 N 台 + 可改家人叫法的提示。
    UI_DEVICES_PAIRED_LINE => "ui.devices_paired_line",

    // ── MOB-29: 删掉的照片会被传回来——两端各一句告知 ──────────────
    // 定调（2026-08-25）：重传是正确行为，不拦；要做的只是让用户知道，
    // 且不做精确归因（人删 / 换库 / 磁盘坏，同一句话都成立）。
    /// Phone-side notice title: assets the phone had confirmed are gone
    /// from the library, so they are being uploaded again.
    UI_MOBILE_REUPLOAD_TITLE => "ui.mobile_reupload_title",
    /// Phone-side notice body — teaches the delete order: kill the source
    /// on the phone first, then delete from the library.
    UI_MOBILE_REUPLOAD_BODY => "ui.mobile_reupload_body",
    /// Desktop-side warning after originals were deleted from the library
    /// in Finder: they come back unless the phone copy goes first.
    UI_LIBRARY_DELETE_WARN => "ui.library_delete_warn",
    /// Dismiss action for the warning above.
    UI_LIBRARY_DELETE_WARN_DISMISS => "ui.library_delete_warn_dismiss",
    // ── NET-13: 设备页——打开该设备存储目录 ────────────────────────
    /// 设备行「打开文件夹」按钮的 title——揭示 originals/<node_id>/。
    UI_DEVICE_OPEN_FOLDER => "ui.device_open_folder",
    /// 打开设备文件夹失败时的错误提示。
    UI_DEVICE_OPEN_FOLDER_FAILED => "ui.device_open_folder_failed",
    /// #413 §7: desktop system notification when the photo library's
    /// volume drops below 5 GiB free. Body takes `{free}` (formatted bytes).
    UI_LOW_SPACE_TITLE => "ui.low_space_title",
    UI_LOW_SPACE_BODY => "ui.low_space_body",

    // ── I18N-03 (#492): 桌面端写死的文案收编 ─────────────────────────
    // 导航/各页正文/向导/lib 纯函数的话术、托盘菜单（Rust 壳按系统语言读
    // 同一份 JSON），以及 Rust 壳经 invoke 回到前端展示的错误（ui.err_*，
    // 以 key + 参数返回，由前端 t() 渲染；底层 {err} 细节原样透传）。
    // 中文值逐字搬自原源码，不改措辞。
    UI_CONN_DIRECT => "ui.conn_direct",
    UI_CONN_RELAY => "ui.conn_relay",
    UI_CONN_OFFLINE_SINCE => "ui.conn_offline_since",
    UI_CONN_OFFLINE => "ui.conn_offline",
    UI_FLOW_DIRECT => "ui.flow_direct",
    UI_FLOW_RELAY => "ui.flow_relay",
    UI_FLOW_UNKNOWN => "ui.flow_unknown",
    UI_PRESENCE_ONLINE => "ui.presence_online",
    UI_PRESENCE_RECENT => "ui.presence_recent",
    UI_PRESENCE_JUST_NOW => "ui.presence_just_now",
    UI_PRESENCE_WAITING => "ui.presence_waiting",
    UI_TIME_JUST_NOW => "ui.time_just_now",
    UI_TIME_TODAY => "ui.time_today",
    UI_TIME_YESTERDAY => "ui.time_yesterday",
    UI_TIME_WEEKDAY => "ui.time_weekday",
    UI_WEEKDAY_SUN => "ui.weekday_sun",
    UI_WEEKDAY_MON => "ui.weekday_mon",
    UI_WEEKDAY_TUE => "ui.weekday_tue",
    UI_WEEKDAY_WED => "ui.weekday_wed",
    UI_WEEKDAY_THU => "ui.weekday_thu",
    UI_WEEKDAY_FRI => "ui.weekday_fri",
    UI_WEEKDAY_SAT => "ui.weekday_sat",
    UI_TIME_MINUTES_AGO => "ui.time_minutes_ago",
    UI_TIME_HOURS_AGO => "ui.time_hours_ago",
    UI_TIME_DAYS_AGO => "ui.time_days_ago",
    UI_PENDING_MANY_TITLE => "ui.pending_many_title",
    UI_PENDING_NEW_HINT => "ui.pending_new_hint",
    UI_PENDING_KNOWN_TITLE => "ui.pending_known_title",
    UI_PENDING_KNOWN_HINT => "ui.pending_known_hint",
    UI_PENDING_ONE_TITLE => "ui.pending_one_title",
    UI_PENDING_SUB_PAIRED_AT => "ui.pending_sub_paired_at",
    UI_PENDING_SUB_PHOTOS => "ui.pending_sub_photos",
    UI_PENDING_SUB_KNOWN => "ui.pending_sub_known",
    UI_DISCONNECTED_AT => "ui.disconnected_at",
    UI_DISCONNECTED => "ui.disconnected",
    UI_DISCONNECTED_HINT => "ui.disconnected_hint",
    UI_STARTUP_MIGRATION_GUIDANCE => "ui.startup_migration_guidance",
    UI_AUDIT_BACKED_UP => "ui.audit_backed_up",
    UI_AUDIT_NEEDS_ATTENTION => "ui.audit_needs_attention",
    UI_AUDIT_SKIPPED => "ui.audit_skipped",
    UI_AUDIT_PART_SEP => "ui.audit_part_sep",
    UI_AUDIT_BACKUP_DONE => "ui.audit_backup_done",
    UI_AUDIT_UNKNOWN_DEVICE => "ui.audit_unknown_device",
    UI_AUDIT_LOCAL => "ui.audit_local",
    UI_AUDIT_PAIR_REQUESTED => "ui.audit_pair_requested",
    UI_AUDIT_PAIR_ACCEPTED => "ui.audit_pair_accepted",
    UI_AUDIT_PAIR_DENIED => "ui.audit_pair_denied",
    UI_AUDIT_REMOVED_EXTERNAL => "ui.audit_removed_external",
    UI_AUDIT_RENAMED_FROM_TO => "ui.audit_renamed_from_to",
    UI_AUDIT_RENAMED => "ui.audit_renamed",
    UI_AUDIT_REVOKED => "ui.audit_revoked",
    UI_AUDIT_UNPAIRED => "ui.audit_unpaired",
    UI_AUDIT_MERGED => "ui.audit_merged",
    UI_AUDIT_RECONCILED => "ui.audit_reconciled",
    UI_AUDIT_UNKNOWN => "ui.audit_unknown",
    UI_WIZARD_CHOOSE_FOLDER_TITLE => "ui.wizard_choose_folder_title",
    UI_WIZARD_SAVE_FAILED => "ui.wizard_save_failed",
    UI_WIZARD_DAEMON_NOT_STARTED => "ui.wizard_daemon_not_started",
    UI_WIZARD_START_FAILED => "ui.wizard_start_failed",
    UI_WIZARD_STEP_LIBRARY => "ui.wizard_step_library",
    UI_WIZARD_STEP_SLEEP => "ui.wizard_step_sleep",
    UI_WIZARD_STEP_SERVICE => "ui.wizard_step_service",
    UI_WIZARD_LIBRARY_TITLE => "ui.wizard_library_title",
    UI_WIZARD_LIBRARY_BODY_MAC => "ui.wizard_library_body_mac",
    UI_WIZARD_LIBRARY_BODY_WIN => "ui.wizard_library_body_win",
    UI_WIZARD_CHANGE_FOLDER => "ui.wizard_change_folder",
    UI_WIZARD_USE_DEFAULT => "ui.wizard_use_default",
    UI_WIZARD_LIBRARY_TIP_MAC => "ui.wizard_library_tip_mac",
    UI_WIZARD_LIBRARY_TIP_WIN => "ui.wizard_library_tip_win",
    UI_WIZARD_CONTINUE => "ui.wizard_continue",
    UI_WIZARD_SLEEP_TITLE => "ui.wizard_sleep_title",
    UI_WIZARD_SLEEP_BODY => "ui.wizard_sleep_body",
    UI_WIZARD_SLEEP_NEVER => "ui.wizard_sleep_never",
    UI_WIZARD_CHECK_PASSED => "ui.wizard_check_passed",
    UI_WIZARD_SLEEP_ON => "ui.wizard_sleep_on",
    UI_WIZARD_SLEEP_MINUTES => "ui.wizard_sleep_minutes",
    UI_WIZARD_SLEEP_FIXING => "ui.wizard_sleep_fixing",
    UI_WIZARD_SLEEP_FIX => "ui.wizard_sleep_fix",
    UI_WIZARD_OPEN_POWER_SETTINGS => "ui.wizard_open_power_settings",
    UI_WIZARD_SLEEP_FIX_FAILED_MAC => "ui.wizard_sleep_fix_failed_mac",
    UI_WIZARD_SLEEP_FIX_FAILED_WIN => "ui.wizard_sleep_fix_failed_win",
    UI_WIZARD_POWER_UNKNOWN => "ui.wizard_power_unknown",
    UI_WIZARD_BACK => "ui.wizard_back",
    UI_WIZARD_SERVICE_TITLE => "ui.wizard_service_title",
    UI_WIZARD_SERVICE_BODY => "ui.wizard_service_body",
    UI_WIZARD_ASKS_LABEL => "ui.wizard_asks_label",
    UI_WIZARD_ASKS_WIN => "ui.wizard_asks_win",
    UI_WIZARD_WONT_LABEL => "ui.wizard_wont_label",
    UI_WIZARD_WONT => "ui.wizard_wont",
    UI_WIZARD_BLOCKED_LABEL => "ui.wizard_blocked_label",
    UI_WIZARD_BLOCKED_MAC => "ui.wizard_blocked_mac",
    UI_WIZARD_BLOCKED_WIN => "ui.wizard_blocked_win",
    UI_WIZARD_FINISH => "ui.wizard_finish",
    UI_NOTICE_CLOSE => "ui.notice_close",
    UI_NAV_OVERVIEW => "ui.nav_overview",
    UI_NAV_DEVICES => "ui.nav_devices",
    UI_NAV_LOG => "ui.nav_log",
    UI_DEVICE_NO_BACKUP_DAYS => "ui.device_no_backup_days",
    UI_DEVICE_NEEDS_ATTENTION => "ui.device_needs_attention",
    UI_DEVICE_LAST_BACKUP => "ui.device_last_backup",
    UI_DEVICE_NEVER_BACKED_UP => "ui.device_never_backed_up",
    UI_PAIR_STRING_COPIED => "ui.pair_string_copied",
    UI_TRAY_HINT_BODY => "ui.tray_hint_body",
    UI_TRAY_HINT_TITLE => "ui.tray_hint_title",
    UI_NO_UPDATE => "ui.no_update",
    UI_REVEAL_FAILED => "ui.reveal_failed",
    UI_SERVICE_RUNNING_LONG => "ui.service_running_long",
    UI_OVERVIEW_TITLE_COUNT => "ui.overview_title_count",
    UI_OVERVIEW_TITLE => "ui.overview_title",
    UI_OVERVIEW_LAST_BACKUP => "ui.overview_last_backup",
    UI_OVERVIEW_LIBRARY_COUNT => "ui.overview_library_count",
    UI_BACKUP_STATUS => "ui.backup_status",
    UI_WATER_MORE_OK => "ui.water_more_ok",
    UI_ADD_DEVICE_BODY => "ui.add_device_body",
    UI_RECENT_ACTIVITY => "ui.recent_activity",
    UI_NO_ACTIVITY => "ui.no_activity",
    UI_ALL_ACTIVITY => "ui.all_activity",
    UI_REMOVED_DEVICES => "ui.removed_devices",
    UI_DEVICES_FOOTNOTE => "ui.devices_footnote",
    UI_PHOTOS_REFRESHING => "ui.photos_refreshing",
    UI_PHOTOS_REFRESH => "ui.photos_refresh",
    UI_PHOTOS_LOADING => "ui.photos_loading",
    UI_PHOTO_VIEW_LARGE => "ui.photo_view_large",
    UI_LOADING => "ui.loading",
    UI_PHOTOS_FOOTNOTE => "ui.photos_footnote",
    UI_LOG_SUBTITLE => "ui.log_subtitle",
    UI_LOG_EMPTY => "ui.log_empty",
    UI_LOG_FOOTNOTE => "ui.log_footnote",
    UI_LIBRARY => "ui.library",
    UI_DISK_SPACE => "ui.disk_space",
    UI_DISK_FREE_OF_TOTAL => "ui.disk_free_of_total",
    UI_LIBRARY_CHANGE_HINT => "ui.library_change_hint",
    UI_SOFTWARE_UPDATE => "ui.software_update",
    UI_CHECK_UPDATE => "ui.check_update",
    UI_PAIR_QR_TITLE => "ui.pair_qr_title",
    UI_PAIR_QR_BODY => "ui.pair_qr_body",
    UI_REFRESH_QR => "ui.refresh_qr",
    UI_CLOSE => "ui.close",
    UI_PAIR_GENERATING => "ui.pair_generating",
    UI_VIDEO_LOAD_FAILED => "ui.video_load_failed",
    UI_TRAY_OPEN => "ui.tray_open",
    /// #550: tray menu entry that exports the diagnostics bundle.
    UI_TRAY_EXPORT_LOGS => "ui.tray_export_logs",
    UI_TRAY_QUIT => "ui.tray_quit",
    UI_ERR_SOCKET_NAME => "ui.err_socket_name",
    UI_ERR_CONNECT => "ui.err_connect",
    UI_ERR_SEND => "ui.err_send",
    UI_ERR_READ_RESPONSE => "ui.err_read_response",
    UI_ERR_NO_DAEMON => "ui.err_no_daemon",
    UI_ERR_DAEMON_UNRESPONSIVE => "ui.err_daemon_unresponsive",
    UI_ERR_IPC_THREAD_SPAWN => "ui.err_ipc_thread_spawn",
    UI_ERR_IPC_THREAD_EXIT => "ui.err_ipc_thread_exit",
    UI_ERR_NOT_JSON => "ui.err_not_json",
    UI_ERR_SLEEP_FIX_UNSUPPORTED => "ui.err_sleep_fix_unsupported",
    UI_ERR_AUTH_CANCELLED => "ui.err_auth_cancelled",
    UI_ERR_SLEEP_FIX_FAILED => "ui.err_sleep_fix_failed",
    UI_ERR_SIDECAR_NOT_DAEMON => "ui.err_sidecar_not_daemon",
    UI_ERR_SIDECAR_EXIT_CODE => "ui.err_sidecar_exit_code",
    UI_ERR_SIDECAR_VERSION_TIMEOUT => "ui.err_sidecar_version_timeout",
    UI_ERR_SIDECAR_SPAWN => "ui.err_sidecar_spawn",
    UI_ERR_SIDECAR_WAIT => "ui.err_sidecar_wait",
    UI_ERR_SIDECAR_READ => "ui.err_sidecar_read",
    UI_ERR_SIDECAR_MISSING => "ui.err_sidecar_missing",
    UI_ERR_REGISTER_AND_SPAWN => "ui.err_register_and_spawn",
    UI_ERR_STOP_MARK_WRITE => "ui.err_stop_mark_write",
    UI_ERR_STOP_MARK_CLEAR => "ui.err_stop_mark_clear",
    UI_ERR_STOP_THREAD => "ui.err_stop_thread",
    UI_ERR_RESPAWN => "ui.err_respawn",
    UI_ERR_KILL_OLD => "ui.err_kill_old",
    UI_ERR_RESTART => "ui.err_restart",
    UI_ERR_NOT_REVIVED => "ui.err_not_revived",
    UI_WIZARD_NOTICE_ONLY_LABEL => "ui.wizard_notice_only_label",
    UI_WIZARD_AUTOSTART_NOTICE_MAC => "ui.wizard_autostart_notice_mac",
    UI_WIZARD_ALLOW_LABEL => "ui.wizard_allow_label",
    UI_WIZARD_LOCAL_NETWORK_MAC => "ui.wizard_local_network_mac",
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_contains_every_constant() {
        for key in [
            ERR_NOT_AUTHORIZED,
            ERR_NOT_PAIRED,
            ERR_DISK_FULL,
            ERR_UNSUPPORTED,
            ERR_BACKUP_FAILED,
            ERR_PAIR_EXPIRED,
            ERR_PAIR_RESTARTED,
            DIAG_ONLINE_DIRECT,
            DIAG_ONLINE_RELAY,
            DIAG_STORAGE_OFFLINE,
            DIAG_INDEXING,
            DIAG_PAIRING,
            DIAG_DESKTOP_STORAGE_OFFLINE,
            DIAG_DESKTOP_PAIRING,
            DIAG_DESKTOP_INDEXING,
            DIAG_DESKTOP_DISK_FULL,
            UI_OFFLINE_BANNER,
            UI_OFFLINE_ACTION,
            UI_START_SERVICE,
            UI_STARTING,
            UI_REFRESH_HINT,
            UI_PAIRED_COUNT,
            UI_REVOKED_COUNT,
            UI_PENDING_PAIRS,
            UI_ALLOW,
            UI_ALLOW_RECONNECT,
            UI_DENY,
            UI_ADD_DEVICE,
            UI_GENERATE_QR,
            UI_QR_FALLBACK,
            UI_QR_HINT,
            UI_QR_PHONE_VERSION,
            UI_DEVICES,
            UI_NO_DEVICES,
            UI_REVOKED_TAG,
            UI_REMOVE,
            UI_SETTINGS,
            UI_OPEN_LIBRARY,
            UI_CHANGE_LIBRARY,
            UI_LOGS_HINT,
            UI_STOP_SERVICE,
            UI_STOP_HINT,
            UI_STOP_CONFIRM_TITLE,
            UI_STOP_CONFIRM_BODY,
            UI_SERVICE_RUNNING,
            UI_SERVICE_STOPPED,
            UI_STOP_FAILED,
            UI_START_FAILED,
            UI_PAIR_FAILED,
            UI_PAIR_ALLOWED,
            UI_PAIR_DENIED,
            UI_CONFIRM_FAILED,
            UI_REVOKE_CONFIRM_TITLE,
            UI_REVOKE_CONFIRM_BODY,
            UI_REVOKED,
            UI_REVOKE_FAILED,
            UI_RENAME,
            UI_RENAME_SAVED,
            UI_RENAME_FAILED,
            UI_OPEN_FAILED,
            UI_CHANGE_TITLE,
            UI_CHANGE_BODY,
            UI_CHANGE_SAVED,
            UI_SAVE_FAILED,
            UI_LOGS_EXPORTED,
            UI_EXPORT_FAILED,
            UI_STATUS,
            UI_LIBRARY_DIR_UNKNOWN,
            UI_UPDATE_AVAILABLE,
            UI_UPDATE_INSTALLED,
            UI_UPDATE_FAILED,
            UI_UPDATE_CHECK_FAILED,
            UI_UPDATE_FAILED_FILE_LOCKED,
            UI_RESTART_SERVICE,
            UI_RESTART_SERVICE_BTN,
            UI_RESTARTING_SERVICE,
            UI_RESTART_SERVICE_HINT,
            UI_RESTART_SERVICE_CONFIRM_TITLE,
            UI_RESTART_SERVICE_CONFIRM_BODY,
            UI_RESTART_SERVICE_OK,
            UI_RESTART_SERVICE_NO_CHANGE,
            UI_RESTART_SERVICE_STARTED,
            UI_RESTART_SERVICE_FAILED,
            UI_ENV_BADGE_TEST,
            UI_NAV_PHOTOS,
            UI_PHOTOS_COUNT,
            UI_PHOTOS_TODAY,
            UI_PHOTOS_YESTERDAY,
            UI_PHOTOS_WEEK,
            UI_PHOTOS_MONTH,
            UI_PHOTOS_EARLIER,
            UI_PHOTOS_EMPTY,
            UI_PHOTOS_OPEN_IN_FINDER,
            UI_PHOTOS_COUNT_PATH,
            UI_PHOTOS_OPEN_LIBRARY,
            UI_PENDING_BANNER_TEXT,
            UI_DEVICES_PAIRED_LINE,
            UI_MOBILE_REUPLOAD_TITLE,
            UI_MOBILE_REUPLOAD_BODY,
            UI_LIBRARY_DELETE_WARN,
            UI_LIBRARY_DELETE_WARN_DISMISS,
            UI_DEVICE_OPEN_FOLDER,
            UI_DEVICE_OPEN_FOLDER_FAILED,
            UI_LOW_SPACE_TITLE,
            UI_LOW_SPACE_BODY,
            UI_CONN_DIRECT,
            UI_CONN_RELAY,
            UI_CONN_OFFLINE_SINCE,
            UI_CONN_OFFLINE,
            UI_FLOW_DIRECT,
            UI_FLOW_RELAY,
            UI_FLOW_UNKNOWN,
            UI_PRESENCE_ONLINE,
            UI_PRESENCE_RECENT,
            UI_PRESENCE_JUST_NOW,
            UI_PRESENCE_WAITING,
            UI_TIME_JUST_NOW,
            UI_TIME_TODAY,
            UI_TIME_YESTERDAY,
            UI_TIME_WEEKDAY,
            UI_WEEKDAY_SUN,
            UI_WEEKDAY_MON,
            UI_WEEKDAY_TUE,
            UI_WEEKDAY_WED,
            UI_WEEKDAY_THU,
            UI_WEEKDAY_FRI,
            UI_WEEKDAY_SAT,
            UI_TIME_MINUTES_AGO,
            UI_TIME_HOURS_AGO,
            UI_TIME_DAYS_AGO,
            UI_PENDING_MANY_TITLE,
            UI_PENDING_NEW_HINT,
            UI_PENDING_KNOWN_TITLE,
            UI_PENDING_KNOWN_HINT,
            UI_PENDING_ONE_TITLE,
            UI_PENDING_SUB_PAIRED_AT,
            UI_PENDING_SUB_PHOTOS,
            UI_PENDING_SUB_KNOWN,
            UI_DISCONNECTED_AT,
            UI_DISCONNECTED,
            UI_DISCONNECTED_HINT,
            UI_STARTUP_MIGRATION_GUIDANCE,
            UI_AUDIT_BACKED_UP,
            UI_AUDIT_NEEDS_ATTENTION,
            UI_AUDIT_SKIPPED,
            UI_AUDIT_PART_SEP,
            UI_AUDIT_BACKUP_DONE,
            UI_AUDIT_UNKNOWN_DEVICE,
            UI_AUDIT_LOCAL,
            UI_AUDIT_PAIR_REQUESTED,
            UI_AUDIT_PAIR_ACCEPTED,
            UI_AUDIT_PAIR_DENIED,
            UI_AUDIT_REMOVED_EXTERNAL,
            UI_AUDIT_RENAMED_FROM_TO,
            UI_AUDIT_RENAMED,
            UI_AUDIT_REVOKED,
            UI_AUDIT_UNPAIRED,
            UI_AUDIT_MERGED,
            UI_AUDIT_RECONCILED,
            UI_AUDIT_UNKNOWN,
            UI_WIZARD_CHOOSE_FOLDER_TITLE,
            UI_WIZARD_SAVE_FAILED,
            UI_WIZARD_DAEMON_NOT_STARTED,
            UI_WIZARD_START_FAILED,
            UI_WIZARD_STEP_LIBRARY,
            UI_WIZARD_STEP_SLEEP,
            UI_WIZARD_STEP_SERVICE,
            UI_WIZARD_LIBRARY_TITLE,
            UI_WIZARD_LIBRARY_BODY_MAC,
            UI_WIZARD_LIBRARY_BODY_WIN,
            UI_WIZARD_CHANGE_FOLDER,
            UI_WIZARD_USE_DEFAULT,
            UI_WIZARD_LIBRARY_TIP_MAC,
            UI_WIZARD_LIBRARY_TIP_WIN,
            UI_WIZARD_CONTINUE,
            UI_WIZARD_SLEEP_TITLE,
            UI_WIZARD_SLEEP_BODY,
            UI_WIZARD_SLEEP_NEVER,
            UI_WIZARD_CHECK_PASSED,
            UI_WIZARD_SLEEP_ON,
            UI_WIZARD_SLEEP_MINUTES,
            UI_WIZARD_SLEEP_FIXING,
            UI_WIZARD_SLEEP_FIX,
            UI_WIZARD_OPEN_POWER_SETTINGS,
            UI_WIZARD_SLEEP_FIX_FAILED_MAC,
            UI_WIZARD_SLEEP_FIX_FAILED_WIN,
            UI_WIZARD_POWER_UNKNOWN,
            UI_WIZARD_BACK,
            UI_WIZARD_SERVICE_TITLE,
            UI_WIZARD_SERVICE_BODY,
            UI_WIZARD_ASKS_LABEL,
            UI_WIZARD_ASKS_WIN,
            UI_WIZARD_WONT_LABEL,
            UI_WIZARD_WONT,
            UI_WIZARD_BLOCKED_LABEL,
            UI_WIZARD_BLOCKED_MAC,
            UI_WIZARD_BLOCKED_WIN,
            UI_WIZARD_FINISH,
            UI_NOTICE_CLOSE,
            UI_NAV_OVERVIEW,
            UI_NAV_DEVICES,
            UI_NAV_LOG,
            UI_DEVICE_NO_BACKUP_DAYS,
            UI_DEVICE_NEEDS_ATTENTION,
            UI_DEVICE_LAST_BACKUP,
            UI_DEVICE_NEVER_BACKED_UP,
            UI_PAIR_STRING_COPIED,
            UI_TRAY_HINT_BODY,
            UI_TRAY_HINT_TITLE,
            UI_NO_UPDATE,
            UI_REVEAL_FAILED,
            UI_SERVICE_RUNNING_LONG,
            UI_OVERVIEW_TITLE_COUNT,
            UI_OVERVIEW_TITLE,
            UI_OVERVIEW_LAST_BACKUP,
            UI_OVERVIEW_LIBRARY_COUNT,
            UI_BACKUP_STATUS,
            UI_WATER_MORE_OK,
            UI_ADD_DEVICE_BODY,
            UI_RECENT_ACTIVITY,
            UI_NO_ACTIVITY,
            UI_ALL_ACTIVITY,
            UI_REMOVED_DEVICES,
            UI_DEVICES_FOOTNOTE,
            UI_PHOTOS_REFRESHING,
            UI_PHOTOS_REFRESH,
            UI_PHOTOS_LOADING,
            UI_PHOTO_VIEW_LARGE,
            UI_LOADING,
            UI_PHOTOS_FOOTNOTE,
            UI_LOG_SUBTITLE,
            UI_LOG_EMPTY,
            UI_LOG_FOOTNOTE,
            UI_LIBRARY,
            UI_DISK_SPACE,
            UI_DISK_FREE_OF_TOTAL,
            UI_LIBRARY_CHANGE_HINT,
            UI_SOFTWARE_UPDATE,
            UI_CHECK_UPDATE,
            UI_PAIR_QR_TITLE,
            UI_PAIR_QR_BODY,
            UI_REFRESH_QR,
            UI_CLOSE,
            UI_PAIR_GENERATING,
            UI_VIDEO_LOAD_FAILED,
            UI_TRAY_OPEN,
            UI_TRAY_EXPORT_LOGS,
            UI_TRAY_QUIT,
            UI_ERR_SOCKET_NAME,
            UI_ERR_CONNECT,
            UI_ERR_SEND,
            UI_ERR_READ_RESPONSE,
            UI_ERR_NO_DAEMON,
            UI_ERR_DAEMON_UNRESPONSIVE,
            UI_ERR_IPC_THREAD_SPAWN,
            UI_ERR_IPC_THREAD_EXIT,
            UI_ERR_NOT_JSON,
            UI_ERR_SLEEP_FIX_UNSUPPORTED,
            UI_ERR_AUTH_CANCELLED,
            UI_ERR_SLEEP_FIX_FAILED,
            UI_ERR_SIDECAR_NOT_DAEMON,
            UI_ERR_SIDECAR_EXIT_CODE,
            UI_ERR_SIDECAR_VERSION_TIMEOUT,
            UI_ERR_SIDECAR_SPAWN,
            UI_ERR_SIDECAR_WAIT,
            UI_ERR_SIDECAR_READ,
            UI_ERR_SIDECAR_MISSING,
            UI_ERR_REGISTER_AND_SPAWN,
            UI_ERR_STOP_MARK_WRITE,
            UI_ERR_STOP_MARK_CLEAR,
            UI_ERR_STOP_THREAD,
            UI_ERR_RESPAWN,
            UI_ERR_KILL_OLD,
            UI_ERR_RESTART,
            UI_ERR_NOT_REVIVED,
            UI_WIZARD_NOTICE_ONLY_LABEL,
            UI_WIZARD_AUTOSTART_NOTICE_MAC,
            UI_WIZARD_ALLOW_LABEL,
            UI_WIZARD_LOCAL_NETWORK_MAC,
        ] {
            assert!(ALL.contains(&key), "{key} missing from ALL");
        }
        assert_eq!(ALL.len(), 279);
    }

    #[test]
    fn keys_are_unique_and_well_formed() {
        let mut seen = std::collections::HashSet::new();
        for key in ALL {
            assert!(seen.insert(key), "duplicate msg_key: {key}");
            assert!(
                key.chars()
                    .all(|c| c.is_ascii_lowercase() || c == '.' || c == '_'),
                "msg_key must be lowercase dotted snake_case: {key}"
            );
            assert!(
                key.starts_with("err.") || key.starts_with("diag.") || key.starts_with("ui."),
                "msg_key must live under err.*, diag.* or ui.*: {key}"
            );
        }
    }
}
