//! REBUILD-02 durable state for one native iroh-blobs delivery at a time.
//!
//! The grant is the Desktop-side authority for an item tuple. It deliberately
//! records the pairing epoch, lease, and BLAKE3 hash together, so an old
//! phone-side retry cannot be mistaken for the current item. Completion is a
//! separate durable transition made only after materialization.

use std::collections::HashSet;

use sqlx::Row;

use crate::{Db, Result};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FlowGrant {
    pub node_id: Vec<u8>,
    pub queue_sequence: i64,
    pub pairing_epoch: String,
    pub lease_token: String,
    pub content_hash: Vec<u8>,
    pub file_name: String,
    pub media_type: String,
    pub provider: String,
    pub state: FlowGrantState,
    pub receipt_id: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlowGrantState {
    Active,
    Cancelled,
    Completed,
}

impl FlowGrantState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Cancelled => "cancelled",
            Self::Completed => "completed",
        }
    }

    fn from_db(value: &str) -> Self {
        match value {
            "active" => Self::Active,
            "cancelled" => Self::Cancelled,
            "completed" => Self::Completed,
            _ => Self::Cancelled,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FlowReceipt {
    pub receipt_id: String,
    pub pairing_epoch: String,
    pub lease_token: String,
    pub content_hash: Vec<u8>,
}

impl Db {
    /// Pairing epochs are generated by the accepted pairing flow and stored on
    /// the paired device row. `None` is intentionally not treated as a match:
    /// legacy pairings must re-pair before they can use the new delivery flow.
    pub async fn pairing_epoch(&self, node_id: &[u8]) -> Result<Option<String>> {
        let epoch: Option<Option<String>> = sqlx::query_scalar(
            "SELECT pairing_epoch FROM device WHERE node_id = ? AND revoked = 0",
        )
        .bind(node_id)
        .fetch_optional(self.pool())
        .await?;
        Ok(epoch.flatten())
    }

    /// Rotate the current pairing epoch after an owner-approved pairing.
    pub async fn set_pairing_epoch(&self, node_id: &[u8], epoch: &str) -> Result<bool> {
        let result =
            sqlx::query("UPDATE device SET pairing_epoch = ? WHERE node_id = ? AND revoked = 0")
                .bind(epoch)
                .bind(node_id)
                .execute(self.pool())
                .await?;
        Ok(result.rows_affected() == 1)
    }

    /// Persist or replace a non-completed single-item grant. Completed rows
    /// are immutable receipts; callers must not overwrite their evidence.
    /// Stamps the resume clock with the wall clock; see
    /// [`Self::upsert_flow_grant_at`].
    pub async fn upsert_flow_grant(&self, grant: &FlowGrant) -> Result<()> {
        self.upsert_flow_grant_at(grant, wall_clock_ms()).await
    }

    /// Same as [`Self::upsert_flow_grant`] with an explicit `now_ms`: an
    /// offer is the phone resuming this tuple, so it restarts the
    /// [`Self::stale_active_flow_grants`] clock (#413 §6).
    pub async fn upsert_flow_grant_at(&self, grant: &FlowGrant, now_ms: i64) -> Result<()> {
        sqlx::query(
            "INSERT INTO flow_delivery
                (node_id, queue_sequence, pairing_epoch, lease_token, content_hash, file_name, media_type, provider, state, receipt_id, last_resumed_ms)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?)
             ON CONFLICT(node_id, pairing_epoch, queue_sequence) DO UPDATE SET
                pairing_epoch = excluded.pairing_epoch,
                lease_token = excluded.lease_token,
                content_hash = excluded.content_hash,
                file_name = excluded.file_name,
                media_type = excluded.media_type,
                provider = excluded.provider,
                state = excluded.state,
                receipt_id = NULL,
                last_resumed_ms = excluded.last_resumed_ms
             WHERE flow_delivery.state != 'completed'",
        )
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.lease_token)
        .bind(&grant.content_hash)
        .bind(&grant.file_name)
        .bind(&grant.media_type)
        .bind(&grant.provider)
        .bind(grant.state.as_str())
        .bind(now_ms)
        .execute(self.pool())
        .await?;
        Ok(())
    }

    /// #413 §6: a status poll that respawns a lost fetch is the phone
    /// actively waiting on this tuple — the same resume fact as an offer.
    /// Only an active row is touched; returns whether one was.
    pub async fn touch_active_flow_grant(&self, grant: &FlowGrant, now_ms: i64) -> Result<bool> {
        let result = sqlx::query(
            "UPDATE flow_delivery SET last_resumed_ms = ?
             WHERE node_id = ? AND queue_sequence = ? AND pairing_epoch = ? AND lease_token = ?
               AND state = 'active'",
        )
        .bind(now_ms)
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.lease_token)
        .execute(self.pool())
        .await?;
        Ok(result.rows_affected() == 1)
    }

    /// #413 §6: active grants whose last resume is older than `cutoff_ms`.
    /// Selection only — the caller decides (e.g. skips a still-running
    /// fetch) and cancels through the guarded [`Self::cancel_flow_grant`].
    pub async fn stale_active_flow_grants(&self, cutoff_ms: i64) -> Result<Vec<FlowGrant>> {
        let rows = sqlx::query(
            "SELECT node_id, queue_sequence, pairing_epoch, lease_token, content_hash, file_name, media_type, provider, state, receipt_id
             FROM flow_delivery WHERE state = 'active' AND last_resumed_ms < ?
             ORDER BY last_resumed_ms",
        )
        .bind(cutoff_ms)
        .fetch_all(self.pool())
        .await?;
        Ok(rows.into_iter().map(flow_grant_from_row).collect())
    }

    /// #413 §7 `index_ok`: the index database is open and its schema
    /// answers a query. Deliberately a read — a health probe must never
    /// contend with ingest for the write lock.
    pub async fn index_health_check(&self) -> Result<()> {
        sqlx::query("SELECT 1 FROM asset LIMIT 1")
            .fetch_optional(self.pool())
            .await?;
        Ok(())
    }

    /// A completed asset may be rediscovered after the phone lost only its
    /// local lease. The receipt stays immutable, but an authenticated caller
    /// with the same epoch and content hash may bind a fresh lease/provider to
    /// replay that receipt without re-fetching the bytes.
    pub async fn rebind_completed_flow_grant(&self, grant: &FlowGrant) -> Result<bool> {
        let result = sqlx::query(
            "UPDATE flow_delivery SET lease_token = ?, provider = ?
             WHERE node_id = ? AND queue_sequence = ? AND pairing_epoch = ?
               AND content_hash = ? AND state = 'completed'",
        )
        .bind(&grant.lease_token)
        .bind(&grant.provider)
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.content_hash)
        .execute(self.pool())
        .await?;
        Ok(result.rows_affected() == 1)
    }

    pub async fn flow_grant(
        &self,
        node_id: &[u8],
        pairing_epoch: &str,
        queue_sequence: i64,
    ) -> Result<Option<FlowGrant>> {
        let row = sqlx::query(
            "SELECT node_id, queue_sequence, pairing_epoch, lease_token, content_hash, file_name, media_type, provider, state, receipt_id
             FROM flow_delivery WHERE node_id = ? AND pairing_epoch = ? AND queue_sequence = ?",
        )
        .bind(node_id)
        .bind(pairing_epoch)
        .bind(queue_sequence)
        .fetch_optional(self.pool())
        .await?;
        Ok(row.map(flow_grant_from_row))
    }

    /// Hashes of Flow items whose durable state still permits/resumes a native
    /// fetch. This is the sole storage-backed protection source for the
    /// flow-blobs GC callback.
    pub async fn active_flow_content_hashes(&self) -> Result<HashSet<[u8; 32]>> {
        let hashes: Vec<Vec<u8>> =
            sqlx::query_scalar("SELECT content_hash FROM flow_delivery WHERE state = 'active'")
                .fetch_all(self.pool())
                .await?;
        Ok(hashes
            .into_iter()
            .filter_map(|hash| hash.try_into().ok())
            .collect())
    }

    /// Record cancellation only if this still is the exact current item.
    pub async fn cancel_flow_grant(&self, grant: &FlowGrant) -> Result<bool> {
        let result = sqlx::query(
            "UPDATE flow_delivery SET state = 'cancelled'
             WHERE node_id = ? AND queue_sequence = ? AND pairing_epoch = ? AND lease_token = ?
               AND content_hash = ? AND provider = ? AND state = 'active'",
        )
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.lease_token)
        .bind(&grant.content_hash)
        .bind(&grant.provider)
        .execute(self.pool())
        .await?;
        Ok(result.rows_affected() == 1)
    }

    /// Atomically record a receipt after the original is materialized. The
    /// exact active tuple is rechecked here, so cancellation/supersession can
    /// never receive a completion receipt.
    pub async fn complete_flow_grant(&self, grant: &FlowGrant, receipt_id: &str) -> Result<bool> {
        let result = sqlx::query(
            "UPDATE flow_delivery SET state = 'completed', receipt_id = ?
             WHERE node_id = ? AND queue_sequence = ? AND pairing_epoch = ? AND lease_token = ?
               AND content_hash = ? AND provider = ? AND state = 'active'",
        )
        .bind(receipt_id)
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.lease_token)
        .bind(&grant.content_hash)
        .bind(&grant.provider)
        .execute(self.pool())
        .await?;
        Ok(result.rows_affected() == 1)
    }

    /// The receipt adapter reads only completed rows; active/cancelled work
    /// is intentionally indistinguishable from no receipt at all.
    pub async fn flow_receipt(
        &self,
        node_id: &[u8],
        pairing_epoch: &str,
        queue_sequence: i64,
    ) -> Result<Option<FlowReceipt>> {
        let row = sqlx::query(
            "SELECT receipt_id, pairing_epoch, lease_token, content_hash
             FROM flow_delivery WHERE node_id = ? AND pairing_epoch = ? AND queue_sequence = ? AND state = 'completed'",
        )
        .bind(node_id)
        .bind(pairing_epoch)
        .bind(queue_sequence)
        .fetch_optional(self.pool())
        .await?;
        Ok(row.map(|row| FlowReceipt {
            receipt_id: row.get("receipt_id"),
            pairing_epoch: row.get("pairing_epoch"),
            lease_token: row.get("lease_token"),
            content_hash: row.get("content_hash"),
        }))
    }
}

fn wall_clock_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

fn flow_grant_from_row(row: sqlx::sqlite::SqliteRow) -> FlowGrant {
    FlowGrant {
        node_id: row.get("node_id"),
        queue_sequence: row.get("queue_sequence"),
        pairing_epoch: row.get("pairing_epoch"),
        lease_token: row.get("lease_token"),
        content_hash: row.get("content_hash"),
        file_name: row.get("file_name"),
        media_type: row.get("media_type"),
        provider: row.get("provider"),
        state: FlowGrantState::from_db(row.get::<String, _>("state").as_str()),
        receipt_id: row.get("receipt_id"),
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::{FlowGrant, FlowGrantState};
    use crate::Db;

    fn grant(hash: u8, state: FlowGrantState, sequence: i64) -> FlowGrant {
        FlowGrant {
            node_id: vec![9; 32],
            queue_sequence: sequence,
            pairing_epoch: "epoch".into(),
            lease_token: format!("lease-{sequence}"),
            content_hash: vec![hash; 32],
            file_name: format!("{sequence}.jpg"),
            media_type: "image/jpeg".into(),
            provider: "provider".into(),
            state,
            receipt_id: None,
        }
    }

    #[tokio::test]
    async fn active_flow_content_hashes_excludes_completed_and_cancelled_grants() {
        let db = Db::open_in_memory().await.unwrap();
        db.upsert_flow_grant(&grant(1, FlowGrantState::Active, 1))
            .await
            .unwrap();
        db.upsert_flow_grant(&grant(2, FlowGrantState::Cancelled, 2))
            .await
            .unwrap();
        db.upsert_flow_grant(&grant(3, FlowGrantState::Completed, 3))
            .await
            .unwrap();

        assert_eq!(
            db.active_flow_content_hashes().await.unwrap(),
            HashSet::from([[1; 32]]),
            "only an active Flow grant may keep a flow-blobs hash alive"
        );
    }

    #[tokio::test]
    async fn completed_grants_from_a_previous_epoch_do_not_occupy_a_rejoin_sequence() {
        let db = Db::open_in_memory().await.unwrap();
        let mut old = grant(1, FlowGrantState::Completed, 1);
        old.pairing_epoch = "epoch-before-rejoin".into();
        db.upsert_flow_grant(&old).await.unwrap();

        let mut renewed = grant(2, FlowGrantState::Active, 1);
        renewed.pairing_epoch = "epoch-after-rejoin".into();
        db.upsert_flow_grant(&renewed).await.unwrap();

        assert_eq!(
            db.flow_grant(&old.node_id, &old.pairing_epoch, old.queue_sequence)
                .await
                .unwrap(),
            Some(old),
            "old completion remains durable history for the stable device"
        );
        assert_eq!(
            db.flow_grant(
                &renewed.node_id,
                &renewed.pairing_epoch,
                renewed.queue_sequence
            )
            .await
            .unwrap(),
            Some(renewed),
            "the new pairing epoch owns an independent sequence namespace"
        );
    }

    /// #413 §6: 超过期限没续传的 active grant 才算过期；completed/cancelled
    /// 永不出现在结果里，刚续传（重新 offer）过的也不算。
    #[tokio::test]
    async fn stale_active_grants_are_selected_by_their_last_resume_time_only() {
        let db = Db::open_in_memory().await.unwrap();
        db.upsert_flow_grant_at(&grant(1, FlowGrantState::Active, 1), 1_000)
            .await
            .unwrap();
        db.upsert_flow_grant_at(&grant(2, FlowGrantState::Active, 2), 5_000)
            .await
            .unwrap();
        db.upsert_flow_grant_at(&grant(3, FlowGrantState::Cancelled, 3), 1_000)
            .await
            .unwrap();
        db.upsert_flow_grant_at(&grant(4, FlowGrantState::Completed, 4), 1_000)
            .await
            .unwrap();

        let stale = db.stale_active_flow_grants(2_000).await.unwrap();
        assert_eq!(stale, vec![grant(1, FlowGrantState::Active, 1)]);

        // Re-offering the same tuple is the resume signal: it refreshes the clock.
        db.upsert_flow_grant_at(&grant(1, FlowGrantState::Active, 1), 9_000)
            .await
            .unwrap();
        assert!(db.stale_active_flow_grants(2_000).await.unwrap().is_empty());

        // A status-driven respawn refreshes it too, but only for an active row.
        assert!(db
            .touch_active_flow_grant(&grant(2, FlowGrantState::Active, 2), 20_000)
            .await
            .unwrap());
        assert!(!db
            .touch_active_flow_grant(&grant(3, FlowGrantState::Active, 3), 20_000)
            .await
            .unwrap());
        assert_eq!(
            db.stale_active_flow_grants(10_000).await.unwrap(),
            vec![grant(1, FlowGrantState::Active, 1)]
        );
    }

    #[tokio::test]
    async fn index_health_check_answers_on_an_open_index() {
        let db = Db::open_in_memory().await.unwrap();
        db.index_health_check().await.unwrap();
        // Counter-proof: a closed index must not report healthy.
        db.pool().close().await;
        assert!(db.index_health_check().await.is_err());
    }
}
