//! REBUILD-02 durable state for one native iroh-blobs delivery at a time.
//!
//! The grant is the Desktop-side authority for an item tuple. It deliberately
//! records the pairing epoch, lease, and BLAKE3 hash together, so an old
//! phone-side retry cannot be mistaken for the current item. Completion is a
//! separate durable transition made only after materialization.

use sqlx::Row;

use crate::{Db, Result};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FlowGrant {
    pub node_id: Vec<u8>,
    pub queue_sequence: i64,
    pub pairing_epoch: String,
    pub lease_token: String,
    pub content_hash: Vec<u8>,
    pub file_name: String,
    pub media_type: String,
    pub provider: String,
    pub state: FlowGrantState,
    pub receipt_id: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlowGrantState {
    Active,
    Cancelled,
    Completed,
}

impl FlowGrantState {
    fn as_str(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Cancelled => "cancelled",
            Self::Completed => "completed",
        }
    }

    fn from_db(value: &str) -> Self {
        match value {
            "active" => Self::Active,
            "cancelled" => Self::Cancelled,
            "completed" => Self::Completed,
            _ => Self::Cancelled,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FlowReceipt {
    pub receipt_id: String,
    pub pairing_epoch: String,
    pub lease_token: String,
    pub content_hash: Vec<u8>,
}

impl Db {
    /// Pairing epochs are generated by the accepted pairing flow and stored on
    /// the paired device row. `None` is intentionally not treated as a match:
    /// legacy pairings must re-pair before they can use the new delivery flow.
    pub async fn pairing_epoch(&self, node_id: &[u8]) -> Result<Option<String>> {
        let epoch: Option<Option<String>> = sqlx::query_scalar(
            "SELECT pairing_epoch FROM device WHERE node_id = ? AND revoked = 0",
        )
        .bind(node_id)
        .fetch_optional(self.pool())
        .await?;
        Ok(epoch.flatten())
    }

    /// Rotate the current pairing epoch after an owner-approved pairing.
    pub async fn set_pairing_epoch(&self, node_id: &[u8], epoch: &str) -> Result<bool> {
        let result =
            sqlx::query("UPDATE device SET pairing_epoch = ? WHERE node_id = ? AND revoked = 0")
                .bind(epoch)
                .bind(node_id)
                .execute(self.pool())
                .await?;
        Ok(result.rows_affected() == 1)
    }

    /// Persist or replace a non-completed single-item grant. Completed rows
    /// are immutable receipts; callers must not overwrite their evidence.
    pub async fn upsert_flow_grant(&self, grant: &FlowGrant) -> Result<()> {
        sqlx::query(
            "INSERT INTO flow_delivery
                (node_id, queue_sequence, pairing_epoch, lease_token, content_hash, file_name, media_type, provider, state, receipt_id)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)
             ON CONFLICT(node_id, queue_sequence) DO UPDATE SET
                pairing_epoch = excluded.pairing_epoch,
                lease_token = excluded.lease_token,
                content_hash = excluded.content_hash,
                file_name = excluded.file_name,
                media_type = excluded.media_type,
                provider = excluded.provider,
                state = excluded.state,
                receipt_id = NULL
             WHERE flow_delivery.state != 'completed'",
        )
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.lease_token)
        .bind(&grant.content_hash)
        .bind(&grant.file_name)
        .bind(&grant.media_type)
        .bind(&grant.provider)
        .bind(grant.state.as_str())
        .execute(self.pool())
        .await?;
        Ok(())
    }

    pub async fn flow_grant(
        &self,
        node_id: &[u8],
        queue_sequence: i64,
    ) -> Result<Option<FlowGrant>> {
        let row = sqlx::query(
            "SELECT node_id, queue_sequence, pairing_epoch, lease_token, content_hash, file_name, media_type, provider, state, receipt_id
             FROM flow_delivery WHERE node_id = ? AND queue_sequence = ?",
        )
        .bind(node_id)
        .bind(queue_sequence)
        .fetch_optional(self.pool())
        .await?;
        Ok(row.map(flow_grant_from_row))
    }

    /// Record cancellation only if this still is the exact current item.
    pub async fn cancel_flow_grant(&self, grant: &FlowGrant) -> Result<bool> {
        let result = sqlx::query(
            "UPDATE flow_delivery SET state = 'cancelled'
             WHERE node_id = ? AND queue_sequence = ? AND pairing_epoch = ? AND lease_token = ?
               AND content_hash = ? AND provider = ? AND state = 'active'",
        )
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.lease_token)
        .bind(&grant.content_hash)
        .bind(&grant.provider)
        .execute(self.pool())
        .await?;
        Ok(result.rows_affected() == 1)
    }

    /// Atomically record a receipt after the original is materialized. The
    /// exact active tuple is rechecked here, so cancellation/supersession can
    /// never receive a completion receipt.
    pub async fn complete_flow_grant(&self, grant: &FlowGrant, receipt_id: &str) -> Result<bool> {
        let result = sqlx::query(
            "UPDATE flow_delivery SET state = 'completed', receipt_id = ?
             WHERE node_id = ? AND queue_sequence = ? AND pairing_epoch = ? AND lease_token = ?
               AND content_hash = ? AND provider = ? AND state = 'active'",
        )
        .bind(receipt_id)
        .bind(&grant.node_id)
        .bind(grant.queue_sequence)
        .bind(&grant.pairing_epoch)
        .bind(&grant.lease_token)
        .bind(&grant.content_hash)
        .bind(&grant.provider)
        .execute(self.pool())
        .await?;
        Ok(result.rows_affected() == 1)
    }

    /// The receipt adapter reads only completed rows; active/cancelled work
    /// is intentionally indistinguishable from no receipt at all.
    pub async fn flow_receipt(
        &self,
        node_id: &[u8],
        queue_sequence: i64,
    ) -> Result<Option<FlowReceipt>> {
        let row = sqlx::query(
            "SELECT receipt_id, pairing_epoch, lease_token, content_hash
             FROM flow_delivery WHERE node_id = ? AND queue_sequence = ? AND state = 'completed'",
        )
        .bind(node_id)
        .bind(queue_sequence)
        .fetch_optional(self.pool())
        .await?;
        Ok(row.map(|row| FlowReceipt {
            receipt_id: row.get("receipt_id"),
            pairing_epoch: row.get("pairing_epoch"),
            lease_token: row.get("lease_token"),
            content_hash: row.get("content_hash"),
        }))
    }
}

fn flow_grant_from_row(row: sqlx::sqlite::SqliteRow) -> FlowGrant {
    FlowGrant {
        node_id: row.get("node_id"),
        queue_sequence: row.get("queue_sequence"),
        pairing_epoch: row.get("pairing_epoch"),
        lease_token: row.get("lease_token"),
        content_hash: row.get("content_hash"),
        file_name: row.get("file_name"),
        media_type: row.get("media_type"),
        provider: row.get("provider"),
        state: FlowGrantState::from_db(row.get::<String, _>("state").as_str()),
        receipt_id: row.get("receipt_id"),
    }
}
