-- DEV-02: 删掉重装指纹。
--
-- `device_hint` 是 DEV-01 为「替换旧身份」服务的启发式指纹
-- （SHA-256(Build.MODEL + ANDROID_ID) 前 8 字节）。设备与身份 1:1 定下之后
-- 那条替换路径整个删掉了（续旧账目 = 两个身份共享一份账，当场破 1:1），
-- 于是这一列再没有任何消费者——而它是手机自报、桌面端无法验证的值，
-- 留着只是持续收集一个没人用的设备标识符。
--
-- 删列同时也把已经收集到的指纹一起清掉。SQLite 3.35+ 支持 DROP COLUMN，
-- 本仓库 libsqlite3-sys 0.30 捆绑的是 3.46。
ALTER TABLE device DROP COLUMN device_hint;
