// Cross-language identity check: the SAME bytes must hash identically
// in Kotlin (io.github.rctcwyvrn:blake3) and Rust (blake3 crate).
// Vectors live in tests/blake3-vectors.json, generated by
// crates/core-index/examples/gen_blake3_vectors.rs.
package com.hawkeyexb.ppass.backup

import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Test

class Blake3VectorTest {

    private fun repoRoot(): File {
        var dir = File(System.getProperty("user.dir"))
        while (!File(dir, "tests/blake3-vectors.json").isFile) {
            dir = dir.parentFile ?: error("blake3-vectors.json not found")
        }
        return dir
    }

    /** Same xorshift generator as the Rust vector producer. */
    private fun xorshiftMiB(seed: Long): ByteArray {
        val out = java.nio.ByteBuffer.allocate(1 shl 20)
            .order(java.nio.ByteOrder.LITTLE_ENDIAN)
        var s = seed
        while (out.remaining() >= 8) {
            s = s xor (s shl 13); s = s xor (s ushr 7); s = s xor (s shl 17)
            out.putLong(s)
        }
        return out.array()
    }

    @Test
    fun kotlinMatchesRustVectors() {
        val vectors = Json.parseToJsonElement(
            File(repoRoot(), "tests/blake3-vectors.json").readText()
        ).jsonArray
        for (v in vectors) {
            val o = v.jsonObject
            val name = o["name"]!!.jsonPrimitive.content
            val expected = o["blake3_hex"]!!.jsonPrimitive.content
            val data = when (name) {
                "empty" -> ByteArray(0)
                "hello" -> "hello".toByteArray()
                "photo_bytes_1MiB_xorshift_5EED202607310053" ->
                    xorshiftMiB(0x5EED_2026_0731_0053L)
                else -> error("unknown vector $name")
            }
            assertEquals(name, o["len"]!!.jsonPrimitive.int, data.size)
            assertEquals("$name (bytes)", expected, blake3Hex(data))
            assertEquals("$name (stream)", expected, blake3Hex(data.inputStream()))
        }
    }
}
